- client/components/download-link/renderers/docx.js
This works but there is a known bug in docx that seems to be duplicating header / footer content:
https://github.com/dolanmiu/docx/issues/259
so you get a repeated page number:
> *BLOCKED* Add page numbers to the footer (WIP)

- client/components/download-link/renderers/docx.js
Since it no longer exists then trying to explicitly export it into a document causes it to throw an error.
> Remove export of protocol setup section

- assets/scss/_editor.scss
So the editor controls stay visible at the top of the screen even when the content is really long.
Use two max height declarations because not all brosers support `vh` yet.
> Prevent text editors getting really tall

- assets/scss/_editor.scss
The max height was added to editors in edit mode to keep the controls on the screen, but needs to be removed from readonly editors because it makes no sense.
> Remove max height on readonly text editors

- client/pages/project.js
The link to the project list makes sense in the drafting tool, but doesn't make sense at all when reviewing a submitted project.
> Remove link to project list from project view

- client/pages/section.js
Because of the way that rich-text editors map `props.value` to `state.value` only on initialisation, if they initialise before they have a value then the state is not recalculated, and so the rich-text editor reimains empty once the data has loaded.
This means that refreshing a page with populated rich-text editors will appear to lose the values.
By waiting for the project to be loaded before allowing any sections to render then this is negated since all values will be present before any RTE components initialise.
> Do not render section if project has not loaded

- views/pdf/v0/protocols/index.jsx
The headings take up space without adding any particular value in terms of understanding of the document.
Removed with agreement of design team.
> Remove headings from exported PDF

- client/components/download-link/renderers/docx.js
There might be more than one node in a paragraph, so make sure we render them all.
Migrated projects have slightly different RTE data structures, and currently throw errors or render incomplete data. In particular some paragraphs contain mutiple nodes, and others have no leaf marks.
> Handle multiple paragraph nodes

- client/components/repeater.js
This was used to handle a deferred data load, but this is now handled in a parent component, and is causing issues when saving local state asynchronously.
Remove the state overwrite so that the local state is the canonical version once the component is initially mounted.
> Remove state overwrite on willReceiveProps

- assets/scss/_editor.scss
- client/components/editor/editor.js
Where an inspector has inserted comments inline into answers in a PPL draft they should be highlighted.
> Highlight inline comments in draft PPLs

- client/schema/v1/index.js
Cos 'or similar' is no longer needed.
> Minor change

- assets/scss/_editor.scss
It's causing line breaks to appear in the middle of words, which makes the content basically impossible to read.
> Fix table line-break CSS

- assets/scss/projects.scss
Horrific hack to hide the checkbox and always show the reveal options
This is necessary to preserve the current data structure and allow the drafting tool to be backwards compatible
> Always show children of permissible purposes

- client/components/diff-window.js
- client/components/review-field.js
- client/components/review.js
`Review` was depending on `DiffWindow` which was depending back on `Review`. `DiffWindow` didn't need _most_ of what was being provided in `Review` anyway.
Refactor out the common elements to remove the circular dependency and have `Review` and `DiffWindow` depend on the single common child component.
> Refactor away circular dependency

- client/pages/sections/protocols/steps.js
`TextEditor` components don't update their internal state when receiving new props, and so reordering steps doesn't update the titles.
By adding a key prop then the components completely re-initialise when the value changes, and so the state is reset to the new value correctly.
See https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key
> Add unique key prop to step title replay

- client/components/repeater.js
In some cases clicking the remove link on an item in a repeater will jump the browser to the top of the page because they use a `href="#"` on a link.
Ensure that the default action is always prevented when removing repeater items.
> Prevent default in repeater component remove item

- client/pages/sections/granted/summary-table.js
Some species entries on protocols are missing a speciesId property. If that happens then render out a dash instead of throwing an error.
> Fix legacy species rendering inside protocol summary

- client/pages/sections/granted/pdf-protocols.js
Some production protocols have null species, which makes things crash when we expect them to always exist.
Same fix as #322 but somewhere else.
> Fix potentially missing label on null species

- client/components/review-field.js
The date was being output without any containing tag, which makes the whitespace look kind of broken.
> Wrap "date" review in a <p> tag

- assets/scss/projects.scss
- client/components/other-species-selector.js
There's a bit of GOVUK inherited styling that strips the margin-bottom off in a very annoying way. Add it back here.
> Fix styling of remove buttons in "other species" selector

- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
Not all PPL sections have fields, and trying to map over sections which do not have fields throws an error.
> Fix mapping over undefined fields

- client/components/changed-badge.js
- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
- client/pages/sections/protocols/steps.js
- client/reducers/changes.js
- client/schema/v0/index.js
- client/schema/v1/index.js
Where fields change inside repeating sections we need to check the complete path to detect if a field has changed, and not simply the top-level field name.
> Fix changed indicators inside protocols

- client/components/editor/list/renderers.js
A blue left border style was added to editors to help highlight the selected list items when editing. This is still being rendered in read-only mode, and looks odd.
Remove the attributes from the rendered HTML when rendering read-only editors.
> Don't render list selection highlights in read-only editors

- client/components/editor/marks/handlers.js
Comment highlighting can't easily be removed in some cases, and in at least one case where the entire content is highlighted cannot be removed at all.
Add a hotkey combination that allows for complete removal of comments without having to delete the content.
> Add hotkey for clearing inline comments

- client/components/download-link/renderers/docx-renderer.js
The default values for table cells' colspan and rowspan values were being erroneously set to large values. Fix that by defaulting them to 1 where the colspan or rowspan are null.
> Fix colspan and rowspans for simple tables

- client/components/download-link/renderers/docx-renderer.js
There are reports of Word on Windows reporting "illegal characters" in exported documents. Some investigation has tracked these down to be related to the percent symbols in table column widths.
Replacing the percentages with very large pixel values still fixes the issue with Pages on MacOS not setting widths correctly, but (hopefully) without causing problems on Word on Windows.
> Use absolute values instead of % for Word export table column widths

- client/actions/projects.js
Sending the before state is not required to be able to apply the diff, and causes ~twice as much data as necessary to be transferred.
> Remove "before" state from diffs

- client/components/field.js
* dont try and add changed indicators for presentational fields.
* If a field doesn't have an onFieldChange method then assume it isn't being persisted
> Bugfix - additional conditions

- client/components/comments/index.js
- client/pages/sections/protocols/legacy-animals.js
This was causing comments to be saved and loaded without a prefix. When loading comments use the prefixed and unprefixed field name and merge the two.
> Add prefix to legacy animals sections

- client/components/scroll-to-top.js
Everything above that is irrelevant when moving between PPL sections, and only forces the user to scroll back down again. Instead scroll up only as far as the top of the download header.
> Scroll only to the top of the download header

- client/components/conditions/index.js
If an automatically added condition has been removed by an inspector then it should be completely removed in non-edit mode and not rendered out to the screen.
> Hide removed conditions when reading licence

- client/components/comments/index.js
There was a fix to include comments made on unprefixed field names for backwards compat with a bugfix for legacy animals section (https://github.com/UKHomeOffice/asl-projects/pull/376)
However, this now results in comments being duplicated for all fields which share a name in a repeated section and at the top level (e.g. `title`).
Fix this by whitelisting only to the original set of fields that was affected - namely those in a legacy PPL animals section.
> Whitelist fields for comment duplication backwards compatability fix

- client/components/download-link/renderers/docx-renderer.js
Occasionally they come back as strings, which means that when they are added together to get the total number of columns in a table then the result is `11111`, which breaks pretty badly for obvious reasons.
Apply a `parseInt` every time we get a `colSpan`/`rowSpan` attribute to make sure that summing the values makes normal mathematical sense.
> Cast all rowSpan/colSpan attributes to integers

- client/components/expanding-panel.js
- client/pages/sections/protocols/sections.js
* remove shouldComponentUpdate from the expanding panel - this was a stupid idea originally intended to stop RTEs rerendering unecessarily
> Bugfix - rerender prevented

- client/components/diff-window.js
* Only try to load field data when a user tries to open the window. Currently all fields load their comparison when the component is rendered, which can result in _a lot_ of requests going at once.
* Add a loading state to handle the case where data is not available yet, instead of just rendering "No answer provided".
* Check if the granted id and the previous id are the same to determine whether to render one tab or two. Currently two tabs are shown even if the previous and granted versions are the same.
> Fix assorted issues with diff window states

- client/components/diff-window.js
Only load the diff content once the user has clicked on the compare link to open the comparison.
For an inspector reviewing a PPL where a lot of changes have been made this fires off a large number of simultaneous requests on render, which can effectively DDoS themselves in certain network conditions and start throwing unexpected error messages.
Instead only make the request to load the content when the window is opened.
Note: this was meant to have come out in #388 but apparently got left behind and I've just seen the DDoS-ing in prod where it sends 30 requests on opening a protocol.
> Don't load diff content on component mount

- client/reducers/comments.js
Comments should be editable as soon as they are added, but because the `isMine` property comes from the server then they are only editable after a refresh.
Set all newly added comments to belong to the current user by default.
> Make newly added comments editable

- client/components/expandable.js
- client/components/expanding-panel.js
Where a PPL has a large number of protocols and steps then the render overhead per keypress becomes very large. By not rendering collapsed sections at all then the performance can be greatly improved.
> Don't render collapsed sections

- client/components/comments/add-comment.js
When a user hits the "Add Comment" button send a keepalive request so that their session does not time out for another half hour.
> Send keepalive when starting comments

- client/actions/session.js
- client/components/comments/add-comment.js
- client/pages/sections/protocols/protocol-sections.js
If someone is typing a comment or navigating inside protocols then ping the server to keep the session alive.
If an inspector is reviewing an incredibly girthy PPL then it's reasonable that they might spend more than half an hour reviewing protocols.
Also make sure that keepalives are occasional. There's no need to ping more than once a minute no mater what the user is doing.
> Keepalive when reviewing PPLs

- client/schema/v1/experience.js
- client/schema/v1/index.js
These are used in PPL transfers to read the field config, but by loading the full schema it includes basically the entire projects app because all the page components are imported.
Pulling the experience fields out into a separate module and importing that directly reduces the bundle size for the task page by ~2-3mb.
> Separate experience fields from full schema

- client/components/repeater.js
- client/pages/sections/protocols/protocols.js
* When adding an item to a repeater, use a prototype object, default {}
> Bugfix - init protocols with lists

- client/constants/conditions.js
- client/pages/sections/protocols/animals.js
- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
- client/schema/v1/index.js
Sometimes speciesDetails contains null entries, this breaks in a lot of places. Filter out null species details to avoid breaking the interface
> Bugfix - handle null speciesDetails

- client/pages/section.js
There's no point trying to calculate the conditions on legacy prjects when they're not going to be saved anywhere and will just get GC-ed away.
> Only calculate the conditions if we're going to save them

- client/schema/v1/index.js
Some licences in prod have ended up with a protocols value of `[null]` which causes this code to break.
Check the protocol exists before reading it.
> Handle null protocols when evaluating section display

- client/components/download-link/renderers/docx-renderer.js
Regex taken from https://www.ryadel.com/en/javascript-remove-xml-invalid-chars-characters-string-utf8-unicode-regex/ (ES6 version)
> Strip any chars disallowed by the xml spec

- client/components/side-nav.js
Set to position relative again on page change (useEffect) as the positions dont get revaluated until scrolling
> Fix sticky nav

- client/components/download-link/renderers/docx-renderer.js
- client/helpers/index.js
If a value is not a string then `replace` fails with an error. Check that values are string values before stripping XML.
> Check values are strings before running replace in Word renderer

- client/components/download-link/renderers/docx-renderer.js
The prod logs have this line throwing an error in certain circumstances. Ensure that the Word download doesn't break when arrays contain falsy values.
> Ignore falsy values when traversing image dimensions

- client/components/download-link/renderers/docx-renderer.js
Also handles the error case where project data is completely empty (`null`).
> Don't render deleted protocols in Word download

- client/components/review-field.js
* Throws in review mode if permissible purposes was previously null
> Bugfix - don't call .include on undefined

- client/actions/messaging.js
If a user is trying to save a project with no session or editing an invalid project then don't show an error message when redirecting them.
> Don't show an error if redirecting a project edit

- client/components/download-link/renderers/docx-renderer.js
Where a section contains repeating and non-repeating fields then _all_ fields are included in the repeater, and then the  non-repeating ones are rendered again.
Add a filter to the repeating section to only include repeated fields when looping over the values.
> Only repeat repeating fields

- client/components/diff-window.js
The diff window's loading state was rendering _super_ slowly for large answers even before the "before" state had been fetched because even in the loading state it performs a `diff` between `undefined` and the current state, which is apparently still a fairly expensive operation.
Move the return of the loading message to above the `diff` call so if no "before" state is available then no computation is carried out.
> Return "Loading" message early from diff window if no before state

- client/pages/sections/granted/project-summary.js
Currently if the establishment has no PEL holder then an error is thrown about trying to destruture their name.
If no PEL holder exists then render a `-` instead.
> Allow PPLs to be held by establishments without a PEL holder

- client/pages/sections/protocols/steps.js
The `protocolId` prop should be the id of the protocol. Previously it was the id of the step.
> Pass correct id to changed indicator

- client/pages/sections/protocols/animals.js
If the label changes in the species selector then a second speciesDetails with the same value is added.
Ensure that the existing entry is used with an updated label instead of a new entry being added.
> Update labels on protocol speciesDetails when label changes in precoded species

- client/actions/projects.js
- client/actions/types.js
- client/components/application-summary.js
- client/components/changed-badge.js
- client/components/location-selector.js
- client/helpers/clean-protocols.js
- client/helpers/get-locations.js
- client/helpers/index.js
- client/reducers/changes.js
If an objective or location at the top level of a project is changed or removed then remove any obselete values from the objectives and locations on the protocols.
Includes a bit of a refactor of comment counts and updated flags to better understand repeated fields.
> Flush protocol locations and objectives when top-level values change

- client/components/scroll-to-top.js
Make the scroll to top handler more specific so that it doesn't respond to hash links, only to changes in the pathname
> Don't scroll to top on hash changes

- client/components/review-field.js
- client/components/review.js
- client/pages/sections/legacy-introduction-review.js
Allow implementations of the Review component to pass children in to override the default ReviewField behaviour to replay values. This allows special case renderings to be handled as one-off implementations rather than bundling everything into the Review component.
Implement this for project continuation on legacy licences.
> Handle special cases in Review component

- assets/scss/projects.scss
- client/pages/sections/protocols/steps.js
Previously it was hidden in the case where some steps were in edit mode, but this was confusing for users who thought it was broken because they couldn't add more steps.
~WIP pending confirmation that we actually want to do this.~
> Always display "Add another" step button when editing

- client/pages/sections/protocols/steps.js
- client/schema/v1/index.js
Not sure how some protocols have ended up having `null` in the steps array, but they do and it causes errors in rendering.
Handle those cases and allow the data to heal itself if it occurs.
> Don't render null steps

- client/pages/sections/protocols/protocols.js
This results in the entire set of protocols being shown as part of the diff and massive PPL payloads.
Instead we'll let the client keep the list, and then filter deleted protocols from data at the point of granting.
> Don't filter out deleted protocols when editing

- client/pages/sections/granted/pdf-protocols.js
Deleted protocols are being rendered into PDF downloads of draft licences. Filter these out before rendering.
> Remove deleted protocols from PDF downloads

- client/components/establishment-selector.js
- client/project-router.js
Skip all the logic about what content to display in what states, and if the licence is granted just return the basic content immediately.
~WIP because I still have some concerns about ASRU users reviewing not-transfers that I want to investigate.~
> Don't show transfer-related content on granted versions

- assets/scss/projects.scss
- client/components/field.js
- client/components/review.js
The repeaters have comment UI on their children, so fields of `type: repeater` shoul not also render a comment UI.
Additionally add some top margin to the comment panel because it's overlapping with the preceding content in a really nasty way.
> Hide comments on field type repeater

- client/components/review-field.js
* this.props was overwriting the value in this component, changed order to use single value
> Bugfix - render reveal children

- client/actions/projects.js
- client/components/editor/index.js
- client/project-router.js
Use a comparison between the saved state and the local state to determine whether to use an `onbeforeunload` function instead of the `isSyncing` which only tracks if an http request is in progress, and is false if the sync is in a debounced state.
Increase the debounce limits on syncing to reduce the total number of syncs when an application is being actively worked on.
> Refactor syncing

- client/project-router.js
The early exit to avoid calculating version state when in readonly mode was causing `isSyncing` to be always false when editing conditions as an inspector. This meant that changes were not reliably saved.
> Check for differences in version state when editing conditions

- client/components/editor/index.js
- client/store.js
* Remove redux logger (but leave it behind to enable it if desired)
* Hard-code null value instead of recalculating per change
* Defer value comparison until after state update to improve UI responsiveness
> Performance improvements

- client/actions/session.js
Throttle doesn't care if it keeps being called, it will still send a keepalive every 30 seconds. Debounce will _never_ send a keepalive if it keeps being called every 29 seconds. This means inspectors who remain entirely active will get timed out.
> Use throttle instead of debounce for keepalive

- client/components/sync-handler.js
- client/project-router.js
Renders an empty div to the page with some classes to indicate sync state to allow for easier tracking in functional tests, and potentially a starting point for future UI as well.
> Move syncing tracking code out of router into separate component

- client/pages/sections/protocols/protocol-sections.js
setting values.title to a default value causes project and savedProject to be out of sync. This causes the page to block redirects and refreshing
> Dont mutate values

- client/actions/messaging.js
- client/actions/projects.js
This allows the local and server versions to be validated for compatibility and incompatible old versions to be prompted to refresh.
> Send version as header to server

- client/pages/sections/protocols/sections.js
Legacy PPLs are always the full application, and so need an extra condition here to prevent them trying to sort by a `granted` property that does not exist.
> Prevent error in PDF rendering legacy PPLs

- client/components/download-link/renderers/docx-renderer.js
Instead of crashing the entire document, replace the failing node with an error block.
Input (with bold text set to throw an error)
Output
> Handle errors in rich text rendering marginally more gracefully

- client/schema/v1/index.js
This became misaligned because the T&E questions were added before continued use changed.
> Use structured input for continued use on T&E licences

- client/pages/sections/nts.js
The `show` property of fields was not being used when getting the list of fields to show in the NTS review section.
This means it was showing all of the fields, both for training licences and non-training licences.
> Filter questions in NTS summary

- client/components/download-link/renderers/docx-renderer.js
Currently 0 years and 6 months is rendered as `5 years 6 months`
> Handle zero year durations in Word download

- client/components/download-link/renderers/docx-renderer.js
Questions that are not asked because they're conditional on other fields should not be rendered into the Word download.
> Don't render hidden fields into word output

- client/components/download-link/renderers/docx-renderer.js
Some rich text input ends up with empty paragraphs between actual paragraphs, which results in masses of whitespace when rendered into word. Don't include any completely empty paragraphs.
> Don't render empty paragraphs into rich text editors

- assets/scss/projects.scss
- client/components/side-nav.js
* Apply sticky styles to side nav in all cases
* Add flexbox to grid columns to ensure equal, full-height columns so sticky styles actually work
* Remove js based sticky fallback because it behaves weirdly with tall menus and short content
> Make project side-navigation sticky

- client/components/establishment-selector.js
- client/pages/sections/establishments.js
All PPL applications are showing a "transfer requested" message, even if they're first time applications. This is because the establishment selector component is now used in first-time applications as well as amendments, but did not have the internal logic updated to reflect this.
Return the simple establishment playback early in review, in the same way as for granted licences. Also remove the double playback of establishment from the establishments review section, so it only appears once.
> Prevent transfer message showing in review mode

- client/components/establishment-selector.js
Previously only the current establishment was ever shown in the review state, which is incorrect for transfers.
Change the review case to ensure that the correct end-state establishment is shown.
> Show correct establishment when reviewing transfer

- client/components/review-fields.js
This is used in some contexts where the redux store does not exist - specifically in asl-pages for reviewing PPL holder changes.
In those cases we need to be able to pass the `project` prop in directly in order to render conditional fields correctly.
> Export non-connected instance of ReviewFields

- .drone.yml
This is not required as this repo is not deployed as a standalone app.
> Remove audit step from drone pipeline

- client/pages/sections/training.js
> Remove double title on training page in readonly

- client/components/fieldset.js
- client/components/species-selector.js
- client/components/toggle-edit.js
- client/helpers/confirm-protocols-affected.js
- client/schema/v1/index.js
Adds an edit toggle to the POLE name / Objective title fields that will trigger a warning message if any protocols will be affected by the change.
> Confirm edit if protocols affected

- assets/scss/_editor.scss
- client/components/editor/format-toolbar.js
* As an input is inside a button, both are focussed in order when tabbing - when the actual icon is highlighted you cannot interacti with it, only when the invisible child input is focussed. Removed tabIndex from parent, and added focus-within style
> Accessibility - RTE image focus

- client/components/diff-window.js
- client/components/review-field.js
- client/helpers/index.js
- client/reducers/changes.js
* allows ReviweField component to have the input `project` set from props and not use the global state - used in the context of changed value comparison to be able to pass in a correct "before" state
* sets `reduction-quantities` as changed in the reducer if any child field changes
* adds a `mapAnimalQuantities` helper to consolidate the correct values for the animal quantities field from a complete project object
> Flag changes in reduction section animal quantities

- client/actions/projects.js
- package.json
If the `objectHash` is undefined then jsondiffpatch uses strict equality to compare elements in arrays, which for text editors - which include a lot of arrays of objects - results in very large diffs for no changes.
If an object doesn't have an id property then use the actual sha256 hash of the object to determine its `objectHash` so that objects are effectively compared by value and not using strict equality.
> Use an actual hash of objects without ids for objectHash diff method

- client/components/diff-window.js
There is a PPL amendment in prod with a 4,500 word answer that contains a lot of changes. Trying to view the diff of that answer using `diffWords` causes the pages to crash.
Replacing `diffWords` with `diffSentences` for long passages vastly improves the performance of the component.
> Use diffSentences to compare long passages

- client/pages/sections/protocols/sections.js
- client/pages/sections/protocols/steps.js
* We show comment count at section level, but not step level, so if there are lots of steps, each one needs to be opened to find new comments
> Bugfix - show comments per step

- client/pages/sections/granted/protocol-steps.js
Trying to `JSON.parse` the value of a rich text editor which is saved as an object throws an error because it's equivalent to `JSON.parse('[object Object]')`.
Instead only `JSON.parse` when the value is already a string.
> Fix step index when values are saved as objects

- client/pages/sections/granted/project-summary.js
This was looking for the field data from the schema, but it's not there because it moved to the NTS section. Hard-code it for the digital view in the same way as it already was for PDFs.
> Hard-code keywords output in granted PPL view

- client/pages/sections/granted/action-plan.js
- client/pages/sections/objectives/review.js
Aims playback is added in ObjectivesReview component as well as the ActionPlan granted view.
Remove it from the latter so it only appears once in granted licences.
> Prevent Aims playback appearing twice in granted licence views

- client/pages/sections/review.js
The project introduction section of a legacy NTS has the `playback` property set to an array. This is handled in some places - e.g. https://github.com/UKHomeOffice/asl-projects/blob/3133f6f29d7e333a0159e20b882d11f8ab01f381/client/pages/sections/index.js#L73 - but was not handled correctly here resulting in an error rendering that section.
> Handle playback fields configured as arrays

- client/components/playback.js
In some cases - for example the Action Plan section on a training licence - the `playback` property of a section is a function that returns null or undefined when no playback is required.
Handle these cases correctly in the playback component.
> Handle case where `playback` on a section is a function

- assets/scss/projects.scss
> Display error alert in front of sticky header

- client/actions/comments.js
- client/actions/projects.js
Actions which send XHR requests when in full application view (i.e. comments, editing conditions/authorisations) need to strip the `/full-application` from the end of the url or the calls fail.
> Fix `basename` property in Full Application view

- client/actions/projects.js
This needs to have the `/full-application` part removed to not respond 404.
> Fix endpoint for loading comparison data

- client/components/diff-window.js
If a fragment of a list selection or plain text input is unchanged then don't add a `diff` class to it because that causes it to be highighted in green.
Only add the class if it is added or removed.
> Don't add `diff` class to unchanged sections

- client/components/diff-window.js
Having this results in an erroneous bullet marker, and it's not there in other places we display this value.
> Remove wrapping `li` from permissible purpose diff

- client/components/review-field.js
Otherwise weird spacing occurs
> Add wrapping `p` tag to licence holder review

- client/components/diff-window.js
This was sending requests for the first diff on load, where it needs to wait until the modal window is opened to avoid adding unnecessary load on the server.
> Only load diffs when the comparison window is open

- client/components/side-nav.js
This was resulting in a changed marker showing against protocols in the side bar when the project title changed.
Do it here and not in the `getFields` helper because I am not confident in that not resultign in unintended side-effects if the same function is used elsewhere.
> Remove `title` from fields that flag a changed indicator on protocols

- client/components/diff-window.js
Using `get` with simple string concatenation fails when the name of the field has dots in - i.e. when inside protocols. Use square bracket notation around the field name so that it handles names with dots in as well.
> Handle field names with dots in them

- client/components/diff-window.js
The server code returns `changedFromLatest` and not `changedFromFirst` when resubmitting an application for the first time, so make sure this logic is reflected here and `changedFromLatest` is preferred.
Otherwise the two conditions conflict and no version for comparison is found when reviewing the first iteration of an application.
> Swap condition to hide changes on first iteration

- client/components/diff-window.js
* Add an explicit `added` class to diff sections which are added
* Reduce slightly verbose and repetitive code to switch classnames
> Clean up class names for rich text diffs

- client/components/field.js
In some contexts - specifically changing a licence holder - the `application` property on the state is not defined, and so this throws an error.
> Handle case where `application` is not defined

- client/project-router.js
I _think_ `project.title` was added to the options for RA to handle the case where there is no version, but it defaults to `Untitled project` and so when editing a draft the title always shows as `Untitled project` even if the draft has been given a title.
By preferring the title on the local version it stays updated when changing the title of the draft.
> Switch preference order of title loading

- assets/scss/projects.scss
* This css hides the back to sections link behind the header when the title is > 1 row
> Bugfix - dont hide sections link

- client/components/download-link/renderers/docx-renderer.js
The condition `not object OR not string` caused the function to always return early and skip the code below.
> Fix images not displaying in docx downloads

- client/components/diff-window.js
- client/components/editor/blocks/index.js
- client/helpers/normalise-whitespace.js
This detects any invisible unicode characters that may appear from copying text from various sources and removes them.
Regex taken from https://github.com/xpl/printable-characters/blob/0b71bb1395659e929ca77ab200eb70691ee514dc/printable-characters.js#L4
> Add normalising function to remove invisible whitespace

- client/components/diff-window.js
This makes them easier to identify in integration tests.
> Add before/after classes to diff window panels

- client/components/diff-window.js
In the case where an amendment is on it's first iteration we only want to show the granted lcience in the comparison window, and not add a second tab for "previous version" which shows the same version.
Check that the previous version is not granted and only show a second tab where there are enough versions to warrant the extra level of comparison.
> Only show one comparison tab when previous and granted versions are the same

- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
Because the changes for repeaters are calculated to include paths at each level e.g. `protocols`, `protocols.<id>`, `protocols.<id>.steps` etc then there's no need to try to enumerate the fields inside these sections - which was being done incorrectly previously - and can simply pass the path to the section level into the changed indicator component.
This vastly reduces the complexity of calculation needed to be done to establish if a repeating section has changed.
> Simplify change flags for nested repeaters

- client/components/editor/index.js
* Normalizing is no longer happening, schema could be defined as part of a plugin before, but now it seems it needs to be defined explicitly. Added schema from list and table plugins
> Bugfix - slate list schema

- client/components/diff-window.js
When an inspector looks at a PPL draft version there may only be one version, so the status check on `iterations[1]` throws. Check the iteration exists before reading the status.
> Prevent error when only one visible version

- client/helpers/index.js
- test/specs/helpers/map-animal-quanities.js
Where a project uses "other" types these are not being correctly rendered in the diff windows for the animal quantities section. Update `mapAnimalQuantities` function to include "other" types.
> Fix diff window display of animal quantities

- client/components/diff-window.js
For text values, if the changes array is empty, still render the RHS for proposed
> Bugfix - proposed text blank

- client/actions/messages.js
- client/actions/projects.js
- client/reducers/application.js
If an edit repeatedly fails to save then increase the timeout before retrying each time, and if it fails more than 5 times consecutively then display a different message and stop retrying.
> Back-off sync error retries and add retry limit

- client/components/editor/blocks/render-block.js
If a rich text element is in read only mode then don't render empty blocks. This prevent inconsistent whitespace between answers where the rich text content has trailing empty paragraphs.
> Trim RTE nodes in read-only mode

- client/components/conditions/add-conditions.js
- client/components/conditions/protocol-conditions.js
- client/components/repeater.js
- client/pages/sections/protocols/animals.js
- client/pages/sections/repeater/index.js
This has been throwing deprecation warning for a while, but seems to now be failing in some contexts. Swap to the recommended approach for accessing the uuid v4 function.
> Remove references to `uuid/v4`

- client/schema/v1/index.js
The default is `Add another ${props.singular}` which means the button has a random upper case A on `Additional`. Automatically lowercasing will break the repeater for `POLEs` so to get rid of the random A then it's easiest to explicitly define the button label.
> Set add another label explicitly for additional establishments

- client/components/species-selector.js
Previously this would read `Specify other type of other rodents` etc. Remove the first "other".
> Remove surplus "Other" from labels

- client/pages/sections/establishments/review.js
The default state of the repeater review is an empty single item, which is incorrect in this context. Hide the establishment repeater completely unless the user has selected "yes" for additional establishments.
> Don't show empty establishment when user answers "no" to Additional Availability

- client/components/application-summary.js
Some sections have a repeating and a non-repeating element. The previous implementation of the comment count was only including comments within the repeating element of the section and not the non-repeating elements.
Where a section has a repeating element use that as the starting value for the "normal" comment counting `reduce` so that all comments are included.
> Fix comment counts for repeater sections

- client/components/application-summary.js
- client/helpers/index.js
- package-lock.json
- package.json
Different sections have different ways of handling repeating field definition and enumeration. Ensure that these are all represented consistently in the comment counting by ensuring that all sections return a complete list of fields with repeating components wildcarded. Previously the protocols section was disregarded, for unknown reasons.
Then filter the comments based on a wildcard match against the field list.
> Fix comment counts for repeating fields

- client/components/changed-badge.js
The previous code expected the changes to contain `protocols` when something inside protocols had changed, which is not the case. The protocol changes are all listed as `protocols.<id>.title` etc, so use minimatch to compare these with `protocols.*.title` as is in the fields array.
> Use minimatch to compare changed fields

- client/schema/v0/index.js
This was causing the custom mapping of fields to break because it was expecting the protocols section to be called `protocols`.
> Fix protocols section name in legacy schema

- client/constants/conditions.js
The transfer of animals question only appears if other establishments are selected, but there have been cases where additional establishments have been added, the transfer question answered as "Yes" and then the additional establishments removed.
In this case the condition should also be removed.
> Restrict trigger for transfer of animals condition

- client/components/download-link/renderers/docx-renderer.js
- client/constants/protocol-conditions.js
- client/pages/sections/granted/pdf-protocols.js
- client/pages/sections/protocols/protocol-conditions.js
- package-lock.json
- package.json
Rather than duplicate the existing constraints content, I have added a basic markdown formatter to the docx renderer.
It uses https://github.com/unifiedjs/unified (which is already in our dependancies as a child of `react-markdown`) to parse the markdown into a syntax tree, and then pushes it through a fairly limited heading/paragraph/bulleted list renderer.
If we were using Slate > 0.5 we could convert the markdown to slate using https://github.com/hanford/remark-slate and then push it through the existing slate parser, but it seemed like a lot more work to do upgrade.
> Add general constraints text (protocol conditions) to application pdf/docx

- client/components/editor/blocks/render-block.js
Empty table cells that were present in the edit view:
were being stripped from the readonly view:
Fix: make sure empty cells get rendered in tables in readonly view.
> Bugfix: Make sure empty table cells get rendered for readonly view

- package-lock.json
- package.json
Just had a few issues with building ASL locally (errors around import vs require of `unified` / `remark-parse`) and noticed that the versions I installed at the top level did not match the major versions used by `react-markdown` and it wasn't de-duping.
I've downgraded the top level versions for now, this seems to clear up the build issue locally. Not sure why it hadn't appeared earlier during dev.
> Use same versions as current react-markdown

- assets/scss/projects.scss
- client/components/editor/table/renderers.js
- package-lock.json
- package.json
It was not obvious that some tables were wider than the space available and therefore needed scrolling.
This adds an always-on horizontal scrollbar if the table overflows it's container.
Supported: Edge, Chrome, Safari
Not supported: Firefox
Needs:
- https://github.com/UKHomeOffice/asl-components/pull/246
> Make horizontal table scroll more obvious for readonly tables

- assets/scss/projects.scss
- package-lock.json
- package.json
Dart Sass does not support extending compound selectors like `a:visited` (which libsass did).
https://sass-lang.com/documentation/breaking-changes/extend-compound
> Compatibility fixes for dart sass

- client/components/comments/add-comment.js
Disable the Save button in the add comment component when clicked so that if a user inadvertently double-clicks then the comment is still only saved once.
Also add a check for completely empty comments.
> Prevent multiple comments if double-clicking

- client/components/editor/blocks/render-block.js
- client/components/editor/image/index.js
Images in PDFs loaded from S3 need to have the full domain defined, so the source needs to be dynamic depending on the defined root URL.
If a `src` attribute is defined then it's almost certainly an old `data:` url, and so should be left intact.
> Build image sources dynamically with configured root URL

- client/pages/sections/establishments/establishments.js
- client/pages/sections/establishments/index.js
- Add new content based on designs below
- Added dynamically updating establishment name if the primary establishment is updated on the previous page
- If it is a draft application it uses the existing transferDraft behaviour when changing the primary establishment, if it is an amendment it goes to the previous page where it allows the user to change the primary establishment
Remade PR from https://github.com/UKHomeOffice/asl-projects/pull/801 as this one was missing content
Screenshot of added content, designs found here: https://w3iqpx.axshare.com/#id=36lndd&p=page_1
When the user chooses to update the primary establishment this is shown on the next page
When they click 'Change' from this page they are returned to the previous screen as it is an amendment
> Improve messaging when adding additional establishments in PPL application

- client/components/conditions/add-conditions.js
Since the addition of reminders, the structure of the emitted value of a `Condition` component is `{ content, reminders }` but the `CustomCondition` component is expected to emit a string.
This resulted in the custom conditions being saved as `[object Object]` rather than the correct value.
> Fix custom conditions

- client/pages/sections/legacy-conditions.js
- client/pages/sections/legacy-introduction-review.js
Since the addition of reminders the edit condition component now emits an object as a value rather than a string so need to save the `content` property of the emitted value otherwise the condition is rendered as `[object Object]`.
Also fix a weird bug where if an inspector visits the introductory details page before editing conditions then the syncing indicator never completes because it thinks there's an unsynced change to the `holder` property on the local values.
> Fix saving legacy conditions

- client/components/editable.js
Previously the content didn't update to match the state, so after every key press the content would be set to the default content. 
Resets the content based on the state so it can be updated.
> Fix bug which doesnt let you edit default conditions

- client/components/sync-handler.js
If the application is in a readonly view then don't put a `Saved` message in the header.
> Don't show saved indicator in readonly state

- client/actions/messaging.js
This was using `r2` but `r2` has been removed in favour of native `fetch` which uses a slightly different API. Convert the POST of error details to the server to use native `fetch` API and so prevent the error handler from throwing an error.
> Fix error handler POST

- client/components/conditions/add-conditions.js
- client/constants/conditions.js
Also allow inspectors to add any project condition to a licence if it's not triggered automatically.
> Fix: trigger 13d condition on domestic fowl

- assets/scss/_editor.scss
Override the `-webkit-user-modify: read-write-plaintext-only` style that is added by slate to the editor element that causes a cursor jumping bug in Chrome 105.
Details at https://github.com/ianstormtaylor/slate/issues/5110
> Fix jumping cursor bug in Chrome 105

- client/components/download-link/renderers/docx-renderer.js
Add error case to add error styling to word doc
> Add error type to apply existing error style

- client/actions/projects.js
- client/helpers/clean-protocols.js
- client/pages/sections/protocols/animals.js
- test/specs/helpers/clean-protocols.js
When saving changes to the project level species, this will now strip the species from `protocol.species` list, but leave the `protocol.speciesDetails` intact.
This will render a changed badge immediately after save against the Protocols section and the relevant protocols.
> Removing species from project level should flag protocol as changed

- client/actions/projects.js
- client/helpers/clean-protocols.js
If you add a protocol without filling out any details, and then go back to the introductory details and change the species then an error is thrown because it tries to filter `protocol.species` when they're not defined.
When the duration field is empty it gets a value set to `{ years: undefined, months: undefined }` which `isEqual` considers to be different to `{}`, but then `diff` returns no difference because it considers them to be equivalent.
When the patch is undefined then no request is sent to the server, but `doneSyncing` is never called, so all future syncs are blocked. Also need to set the saved state to the local state in this case, so that a "change" (not actually a change) in the duration value field does not repeatedly cause attempts to sync.
> Fix syncing bugs with new projects filled out in an odd order

- client/pages/sections/protocols/steps.js
Adds a bit of logic that if it's a reusable step being edited then only the one instance that was clicked on shows as editable and the other instances stay read-only.
This code could use a serious refactor to stop confusing `editable` and `completed` tbh, but not now.
> Only edit one reusable step instance at a time

- assets/scss/projects.scss
- client/actions/projects.js
- client/components/application-summary.js
- client/components/review.js
- client/components/side-nav.js
- client/helpers/reusable-steps.js
- client/helpers/steps.js
- client/pages/sections/granted/protocol-steps.js
- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
- client/pages/sections/protocols/steps.js
- client/schema/v1/index.js
This will now store reusable steps in a property at the top level of the project-versions:
```
"reusableSteps": {
"39b40f1d-0cb3-47b2-8ebe-0306ec2a5ba0": {
"id": "39b40f1d-0cb3-47b2-8ebe-0306ec2a5ba0",
"saved": true,
"title": {
...
},
"adverse": true,
"optional": false,
"reusable": true,
"completed": true,
}
}
```
Where a step within the protocols is using a re-usable step, it will only include the id, and a reusableStepId:
```
"steps": [
{
"id": "39b40f1d-0cb3-47b2-8ebe-0306ec2a5ba0",
"reusableStepId": "39b40f1d-0cb3-47b2-8ebe-0306ec2a5ba0"
}
]
```
**Editing step:**
Now shows new step reference and re-use question
___
**Adding a new step**
When there is at least one re-usable step, then when adding a step the following option is available:
___
**View Step:** 
This now has an option to: …
> ASL-4046 Reusable steps

- client/helpers/steps.js
- client/pages/sections/protocols/steps.js
This handles the case where there is no reference on a reusable step, first falling back to the first 80 characters of the description, then to Unnamed step.
If duplicates exist, it will start appending a number after the reference, description, default.
Adds ordering so the step references are in alphabetical order.
> ASL-4046 - Fallback to truncated title then 'Unnamed step' if no reference on reusable step

- client/components/additional-availability.js
- client/components/playback.js
- client/components/review-fields.js
- client/pages/sections/granted/project-summary.js
- client/pages/sections/granted/protocol-steps.js
- client/pages/sections/legacy-introduction-review.js
- client/pages/sections/objectives/review.js
- client/pages/sections/protocols/steps.js
- client/pages/sections/repeater/review.js
The component previously ignored `className` prop, but now applies it, so in cases where it might accidentally be passed through by passing all field properties to the component explicitly set it to `""`.
> Explicitly set classnames to empty when passing props through to `<Review>` component

- client/components/download-link/renderers/docx-renderer.js
- client/helpers/steps.js
- client/pages/sections/protocols/steps.js
- client/schema/v1/index.js
Couldn't find a better way to identify that it was being generated for a PDF or DOCX for hiding the reusable steps questions so have used the `props.readonly` property as this seemed to make the most sense and already there when PDF, and needed a slight tweak for DOCX.
> ASL-4046 - Add reference + repeated from on pdf / docx step title when re-usable/re-used step

- client/pages/sections/protocols/steps.js
I missed the View latest submission playback when adding the reference and 'repeated from protocol X' to the step headers.
> ASL-4046 - Include reference + repeated from for re-usable/re-used step headers on 'View latest submission' playback

- client/pages/sections/protocols/steps.js
The reusable steps options were incorrectly showing in review mode.
> Don't show reuse options when not editable

- assets/scss/projects.scss
- client/schema/v1/permissible-purpose.js
The bug https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4119 is caused by users clicking a hidden checkbox which then causes flattenReveals to run on the translational research values, giving it it's own section when being reviewed.
Disabling the hidden checkbox stops it from being added to values and will stop this bug happening in the future.
Added styling to stop the disabled checkbox losing opacity
> Disable hidden checkbox to stop translation research being displayed twice

- client/helpers/index.js
This is a fix for users who have already encountered the bug. Checks if translational research is being assessed in the flattener and skips over it.
> Stop flattening translational research options when the invisible checkbox is ticked

- client/schema/v1/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-3263
Removes 'Additional conditions' subtitle as it was duplicated.
> Remove duplicated subtitle on PPL review

- client/pages/sections/granted/protocol-steps.js
Previously the message was only included in the view within the app and not the PDF export
Move h3 so it's included in both
> Move h3 to also be included in pdf export

- client/actions/messaging.js
This should hopefully shed a little more light on what's going on when client sync errors log.
> Send error statuses to error logging endpoint when sync fails

- client/helpers/steps.js
- client/pages/sections/protocols/steps.js
When displaying the steps within the 'View latest submission' screen, the steps will now be collapsed by default. And there is an option to Open all steps (which I missed in the original reusable steps designs)
Have also updated the use of flatMap to use lodash
> ASL-4127 - Default steps to collapsed on 'View latest submission' & add open/close all steps

- client/pages/sections/granted/summary-table.js
- client/pages/sections/protocols/summary-table.js
This should fix the issue where details of a re-usable step are not appearing on the `View summary table (opens in a new tab)` page. It needed to hydrate the steps to pull the information from the reusableSteps where applicable
> ASL-4171 - Show details for re-useable step on protocols summary

- client/actions/messaging.js
- client/actions/projects.js
I have managed to re-create a couple of the errors we are seeing regular alerts for:
**Problem 1:**
If a user is editing a project application (protocols for example) and the user is logged out in another tab (I think the same would happen if the session expired) then when a change is made to the page it will redirect to the login page, but will also try and determine the changes from the response from the server because `window.location.reload()` is being returned. This results in `Cannot read properties of undefined (reading 'changes')`
**Solution**
Have removed the return, so the page will just redirect, and no more of the save logic will be attempted.
**Problem 2** 
When there is a network issue when syncing the project (can recreate by throttling to Offline in Network tab in Chrome), …
> Tweak error reporting on intermittent project sync failure & when login session no longer valid

- client/helpers/steps.js
- client/pages/sections/protocols/sections.js
- client/pages/sections/protocols/steps.js
- package-lock.json
The way reusable steps was set up meant that the comment counter didn't flag new comments made as they were not appended with protocols.protocolId.
Also didn't flag on the protocol or step levels as the regexs looked for steps.stepId rather than reusableStep.stepId
> ASSB-1285-1286: Fix comment count on reusable steps

- client/pages/sections/protocols/steps.js
Fixes an issue where the step reference would be set to 'Undefined (edited)' if a step was:
1) reusable
2) did not have a reference
3) the user clicked 'edit just this step'
Also fixes an issue where '(edited)' would be appended to the step reference every time it was edited, now only adds it if it doesn't already have it appended.
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1287
> Fixes issue with reusable step titles after they are edited

- client/pages/sections/protocols/steps.js
Adds step numbers to the review page as they were lost when reusable steps was introduced.
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1283
> ASSB-1283: Add step numbering to review page

- client/components/editor/index.js
At the moment when the user removes a value from the form the value is set to 'null' rather than null. This causes the rich text editor to break as it tries to use this to fill the editor, rather than the nodes it gets from initialValue('')
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1292
> ASSB-1292: Fix user unable to edit and resubmit PPL transfer

- client/helpers/get-locations.js
- test/specs/helpers/clean-protocols.js
- Do not show additional establishments list if "other-establishments" is `false`
- stops us from showing deselected other establishments
Only showing primary establishment after additional establishments has been deselected:
> Fix "other-establishments" logic

- client/helpers/steps.js
- client/pages/sections/protocols/protocols.js
- client/pages/sections/protocols/steps.js
Add 'protocols.<id>' prefix in a few locations where it was missed for "reusableSteps" fields
This should address some of the discrepancies observed when reusable step fields are commented
> Align naming of reusable step fields when referenced in protocols

- client/components/diff-window.js
- package-lock.json
- package.json
**Missed below scenario in previous testing:**
As soon as the page is loaded we don't see the coloring for in the proposed tab but it appears when switch tabs or refresh the browser, this is not the case with other elements like 'Rich text editor', 'Checkboxes' or 'radio group elements'
https://public-ui.dev.asl.homeoffice.gov.uk/establishments/8201/projects/805f025c-c74f-42b7-b58e-5b1594f49d12/versions/a168fe3e-dff5-4a5c-93e2-831a12a937a4/full-application/aims
> bug: ASL-4532 - Fix initial submission first load issue

- .eslintrc
- client/helpers/index.js
- client/schema/v1/index.js
- package-lock.json
- package.json
- test/specs/helpers/url-markdown.js
* `window.location.href` check still errors trying to access property location on undefined
* Node seems to have special handling for window as `window != undefined ? ...` still errors 🤷🏻‍♂️
* `typeof window === 'undefined' ? ...` does work.
Autoproject tests pass locally when updated to match the new functionality.
Other QOL changes:
* Use `@ukhomeoffice/asl` for eslint - works in CI/CD and workspace.
* `UrlMarkdown` looked like a class name not a function name, and didn't read as specific to keeping animals alive. I've refactored to take the possibly null url as an argument and renamed to look like a function.
> [ASL-4495] Fix for window is undefined

- client/helpers/render-fields-in-protocol.js
- package-lock.json
- package.json
Option in array had option in a nested object, so when the component tried to access the value in the top level object it was undefined.
Switched to use option from predefinedFields so we're not defining that option in two places.
> [ASL-4495] Array of options when missing NTS fate had wrong structure

- client/pages/sections/protocols/protocols.js
When rendering the selected fates options as an unordered list they're expected to be an array.
> [ASL-4495] list of fates fields should be an array

- client/components/review.js
- client/helpers/index.js
- client/schema/v1/index.js
- package-lock.json
- package.json
- test/specs/helpers/url-markdown.js
* Hint in review now rendered as markdown to match logic in form inputs [@ukhomeoffice/react-components](https://github.com/UKHomeOffice/react-components/blob/main/src/forms/input.jsx#L34-L36)
* Building NTS link also needs to account for `full-application` url
* Default options to all. When rendered as field these will always be overridden, but when used to reference how to render options that were selected (e.g. in PDF) it's easiest to have all available, as only selected options actually get shown.
> [ASL-4495]  Fix rendering defects

- client/components/review.js
- package-lock.json
- package.json
- views/pdf/index.jsx
By default, the markdown renders the contents in a paragraph. This created nested paragraphs weren't getting the hint text styling in the pdf. The Markdown component provides functionality to wrap in a span instead when there is a single line which renders with the expected styles.
Also minor code style change that was highlighted by IDE when investigating
> [ASL-4495] Fix PDF styling regression

- client/components/review.js
- package-lock.json
- package.json
When using unwrapSingleLine there were some hints (e.g. aims) with multiple lines that still rendered nested p tags, breaking the PDF styling
> [ASL-4495] Style hints in ReactMarkdown

- client/helpers/has-existing-data-for-checkbox.js
- client/helpers/reset-fields-based-on-checkbox.js
- package-lock.json
- package.json
- test/specs/helpers/has-existing-data-for-checkbox.test.js
- Kept-alive answers count as existing data for kept-alive, set-free, and rehomed
- Deselecting the last of kept-alive, set-free, or rehomed should be what triggers clearing kept-alive answers
- Clearing an NTS checkbox should deselect that option in all protocols (this was what was causing some to be pre-ticked in UAT demo)
- Individual protocols and the protocol section should only be marked as incomplete if there is a change.
> [ASL-4495] Change deselection behavior

- client/schema/index.js
- package-lock.json
- package.json
https://github.com/UKHomeOffice/asl-deployments/blob/failures-22133/tests/actual/E2E-can_submit_a_new_RA-full-chrome-1260x800-dpr-1.png 
When getting subsections for the  'RA' version there is no 'introduction' subsection, so attempting to inject the licence holder field fails.
> [ASSB-1418] Fix accessing fields of undefined when version is RA
