- client/components/download-link/renderers/docx.js
The previous code assumes that nothing other than text is ever put inside a list, and people are authoring with nested list.
TODO: style the nested things in an actually nested way
> Add support for elements nested inside lists

- client/application.js
All changes to questions per protocol, plus a few extra changes elsewhere that I could easily deal with myself.
> Content changes

- client/application.js
Note: this is untested while we wait for a fix for unclickable radio buttons and checkboxes.
> Move conditional questions in protocol experimental design section

- client/schema/v1/index.js
> Annoying changes

- client/schema/v1/index.js
> Ready for deploy

- client/components/editor/text-editor.js
If an image is added which is more than 1mb in size, throw an error and display a message
> Throw an error if importing images which are too large

- client/components/download-link/renderers/docx.js
Decoupled heading styles from document styles (added styles: Section, Question)
Changed section style
Changed question style
Fixed bug showing 'month' for values of 0
Added cover page
Added document exported date
Added protocol numbers
Added page break after each protocol
Fixed bug - spaces when rich text formatting
> Styling improvements to word doc export

- client/schema/v1/index.js
That I can easily do myself for inspectors.
> Minor non-controversial changes

- client/schema/v1/index.js
> More minor changes

- client/schema/v1/index.js
Last set of changes I can make myself.
> Final amends

- client/schema/v1/index.js
Minor update for Show and tell.
> Minor update for Show and tell.

- assets/scss/projects.scss
- client/actions/comments.js
- client/actions/messaging.js
- client/actions/projects.js
- client/components/application-summary.js
- client/components/conditions.js
- client/components/expanding-panel.js
- client/components/side-nav.js
- client/components/static-section.js
- client/constants/conditions.js
- client/helpers/index.js
- client/pages/section.js
- client/pages/sections/conditions.js
- client/pages/sections/protocols/protocols.js
- client/pages/sections/protocols/sections.js
- client/schema/v1/index.js
* added logic to add authorisations and conditions as the draft is being amended
* added logic to show conditions and authorisations if showConditions is passed in on init
* added logic to edit conditions if editConditions is passed in
* added first pass of content and conditionals
> Added authorisations and conditions component

- assets/scss/_editor.scss
In order to prevent style leaking into other places which include `class="comment"`
> Scope comment highlighting styling

- client/schema/v0/index.js
- client/schema/v1/index.js
As per Anthony/Ben Stevens request
> Minor content changes

- assets/scss/projects.scss
- client/actions/projects.js
- client/components/conditions.js
- client/components/editable.js
- client/constants/conditions.js
- client/pages/sections/other-legal-text.js
- client/schema/v1/index.js
- package-lock.json
* updated conditions and authoristions in line with spreadsheet
* added other legal text section
* abstracted editable field component
> Added other legal text section

- client/pages/settings.js
- client/schema/v0/index.js
'Additional' establishments, and changes related to AS-1202
> Minor text changes

- client/pages/sections/other-legal-text.js
* use editConditions to determine whether conditoins should be editable
* render raw condition if not
> Read only conditions

- client/components/review.js
show review content in place of label if present. This is to display retrospective assessment statement rather than yes/no
> Review content

- client/components/editor/index.js
- client/components/editor/marks/handlers.js
> fix onKeyDown

- client/components/editor/format-toolbar.js
- client/components/editor/index.js
- client/components/field.js
- client/components/fieldset.js
- client/components/review-fields.js
- client/components/review.js
- client/schema/v1/index.js
A lot of the components here expect a redux store with certain keys - this prevents them being used outside of this context. Fixed this in ReviewFields and Field
Added new content for experience
> Allow external access

- client/schema/v0/index.js
- client/schema/v1/index.js
As detailed on AS-1583. If a dev could look over this section to ensure that everything would work and all the brackets and commas are in the right place, that'd be great.
> Changes to re-use/continued use

- client/constants/conditions.js
All done.
There's something I haven't done right under 'Establishment licences not meeting Code of Practice'. Probably a missing comma/bracket.
Could a dev check this and let me know what I haven't done properly?
> Cons and Auth changes

- assets/scss/projects.scss
- client/components/comments/comment.js
- client/components/conditions/conditions.js
- client/components/conditions/protocol-conditions.js
- client/components/download-header.js
- client/components/download-link/renderers/docx.js
- client/components/location-selector.js
- client/components/review.js
- client/components/side-nav.js
- client/components/static-section.js
- client/constants/index.js
- client/helpers/index.js
- client/pages/project.js
- client/pages/readonly.js
- client/pages/section.js
- client/pages/sections/granted/action-plan.js
- client/pages/sections/granted/authorisations.js
- client/pages/sections/granted/conditions.js
- client/pages/sections/granted/project-summary.js
- client/pages/sections/granted/protocol-continued.js
- client/pages/sections/granted/protocol-establishments.js
- client/pages/sections/granted/protocol-purpose.js
- client/pages/sections/granted/protocol-steps.js
- client/pages/sections/objectives/review.js
- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/sections.js
- client/schema/index.js
- client/schema/v1/index.js
* Updated protocols to include table
* added granted only sections
* added styles for step index interface
> Digital view of granted licence

- client/components/field.js
* We were relying on props.value for updating a field, instead let each field control its internal state and update project after this changes
> Bugfix for jumping cursor

- client/components/conditions/protocol-conditions.js
- client/components/review-fields.js
- client/pages/sections/granted/protocol-steps.js
Fixed errors thrown by empty protocol steps and missing auths/conditions
> Sometimes granted projects are incomplete

- client/schema/v1/index.js
> Addition to hint text

- assets/scss/_editor.scss
- client/components/diff-window.js
- client/components/editor/index.js
- package-lock.json
- package.json
Compares the string values of the before and after fields and highlights removals and additions on each.
> Implement granular diffs in comparison tooling

- assets/scss/_editor.scss
- client/components/editor/blocks/index.js
- client/components/editor/blocks/render-block.js
- client/components/editor/format-toolbar.js
- client/components/editor/index.js
- client/components/editor/list/index.js
- client/components/editor/list/renderers.js
- package-lock.json
- package.json
* added slate-edit-list fork
* configured plugin
> Nested lists

- client/schema/v1/index.js
> 1 text amend

- client/components/download-link/renderers/docx-renderer.js
- client/components/download-link/renderers/docx.js
- package-lock.json
- package.json
* create matrix representaion of table including colspans and rowspans
* create table with max dimensions
* add content to cells
* pass over matrix again merging rowspans - this needs to happen before horizontal merges so these need to be merged in a separate pass
> Docx tables

- client/schema/v1/index.js
> Typo correction

- client/components/download-link/renderers/docx-renderer.js
If this is the case we should try and render the table as a matrix without merged cells
> Sometime merging cells fails.

- client/components/review-field.js
Duration should default to 5 years 0 months if invalid or missing
> Bugfix - duration rendering

- client/actions/projects.js
- client/actions/types.js
- client/pages/sections/legacy-conditions.js
- client/project-router.js
- client/reducers/application.js
- package-lock.json
- package.json
* only allow one sync at a time, keep syncing until everything up to date
* added unbeforeunload if syncing
* disabled next steps if syncing
> Improve syncing

- client/components/review-field.js
To ensure whitespace renders correctly.
> Wrap permissible purpose "none selected" message in <p> tag

- assets/scss/projects.scss
- client/components/editor/index.js
- client/pages/sections/protocols/sections.js
* Accordion needs expanding panel children, not fragments.
* Added changed label to correct place next to comments
> Fix changed label

- client/actions/messages.js
- client/actions/messaging.js
- client/actions/projects.js
- client/actions/types.js
- client/components/alert.js
- client/project-router.js
- client/reducers/application.js
* Show error message if sync failed
* Show success message if recovering from failed sync
> Added sync messaging

- client/actions/messaging.js
* disable rediect in fetch
* if detect redirect attempted, reload page
> Reload on session expiry

- client/constants/conditions.js
As per https://jira.digital.homeoffice.gov.uk/browse/AS-1912
> Philcontent3107 2

- client/schema/v1/index.js
As requested in https://jira.digital.homeoffice.gov.uk/browse/AS-1951
> minor content update

- client/components/download-link/renderers/docx-renderer.js
- client/components/review-field.js
- client/components/review-fields.js
- client/pages/sections/legacy-introduction-review.js
- client/reducers/index.js
- client/reducers/static.js
- client/schema/index.js
- client/schema/v0/index.js
- client/schema/v1/index.js
1.In introductory details section
*Add PPL holder's name profile link 
2.In .docx add
-Introductory section
*PPL holder's name 
*PPL number
*Primary establishment name
-Establishments page:
*Additional establishment name(s)
*Response to 'Why do you need to use this additional establishments?'
*Response to 'Who will supervise work at this additional establishment?
3.Render default duration
> Render default duration and licence holder name

- client/actions/session.js
- client/pages/readonly.js
- package-lock.json
- package.json
This means that when inspectors are reviewing PPLs that they don't get timed out because they're not hitting the server.
> Add keepalive to readonly project view

- assets/scss/projects.scss
- client/components/conditions/add-conditions.js
- client/components/conditions/conditions.js
- client/components/conditions/index.js
- client/components/retrospective-assessment.js
- client/constants/conditions.js
- client/constants/retrospective-assessment.js
- client/pages/sections/conditions.js
- client/pages/sections/granted/project-summary.js
- client/pages/sections/legacy-conditions.js
- client/schema/v0/index.js
- package-lock.json
- views/pdf/v0/index.jsx
* Added new RA component
* if conditions are met, it is always true and uneditable
* if not then try and get value from legacy
> Refactor - Retrospective Assessment

- client/components/field.js
- client/components/species-selector.js
* pass correct value from state to species selector
* use unique names for each subcategory fieldset
* create unique list of species to be saved
> Bigfix - species selector

- client/constants/conditions.js
Updated continuation auth content to include placeholder for inspector to add licence numbers
> Update condition content

- assets/scss/projects.scss
- client/constants/conditions.js
- client/constants/legal.js
- client/constants/protocol-conditions.js
- client/pages/sections/granted/pdf-protocols.js
- client/pages/sections/protocols/protocol-conditions.js
- client/pages/sections/protocols/review.js
Moves these conditions to be at Protocol summary level in both digital and PDF views.
> Update to surgery, anaesthesia and substance administration conditions

- client/components/comments/comment.js
You can no-longer edit or delete a comment after a task status change.
You can still edit and delete comments added in the current round.
> Only new comments can be deleted / edited

- client/components/comments/comment.js
The current mechanism checks author's name only, which is kinda fragile.
> Use "isMine" property from comments to determine ownership

- assets/scss/projects.scss
- client/components/banner.js
- client/components/error-boundary.js
- client/components/field.js
- client/components/review.js
- client/components/static-section.js
- client/external.js
- client/index.js
- client/pages/readonly.js
- client/pages/section.js
* Added ErrorBoundary component
* Added error handlers at field/review, section and application level
> Feature - error handling

- client/helpers/index.js
Where conditions are auto-added but then edited by an inspector the `path` attribute was being stripped, which resulted in being unable to restore the value from the inpector's side.
Ensure that when the criteria for custom conditions are changed that the paths are preserved.
> Preserve paths on edited conditions

- client/actions/projects.js
Previusly the payload for the conditon sync call was _always_ the project level conditions.
Update so that the Sync method inspects the difference between all conditions when called and sends the first set of conditions that requires saving, and then saves to the saved state locally.
Then repeat until there are no more conditions that require saving.
> Fix protocol level condition/authorisation saving

- client/components/playback.js
* not all sections have fields - dont throw error when playing back from section without fields
> Bugfix - NTS project summary

- client/components/diff-window.js
~Builds on top of #388 which should be merged first~
> Add banner when text value is unchanged

- client/components/editor/index.js
- package-lock.json
- package.json
* bumped slate-edit-list with fix for todo
* swapped order of list and table plugins, to ensure handlers in lists fire first when contained within a table
> Bugfix - undo

- client/pages/sections/protocols/steps.js
Replaced text editor component with ReviewFields to handle read only view with comments
> Bugfix - step title comments

- client/pages/sections/granted/protocol-steps.js
Hide the initial yes/no question and just show the revealed Q&As if the answer is yes.
> Only show revealed adverse questions in readonly view

- client/components/diff-window.js
Dont try and JSON.parse things that aren't JSON
> Bugfix - diff window text fields

- client/pages/sections/protocols/protocols.js
* dont set steps to [] for new protocols on legacy licences
> Bugfix - legacy steps

- client/components/editor/blocks/index.js
- client/components/editor/format-toolbar.js
- client/components/editor/marks/index.js
- package-lock.json
- package.json
* added button to toolbar
* clear marks in selection
* find ancestor element, find all child nodes and unwrap up to ancestor
* treat table cells like new document
> Feature - clear formatting

- client/components/download-link/renderers/docx-renderer.js
- client/components/other-species-selector.js
- client/components/species-selector.js
- client/constants/species.js
- client/pages/sections/granted/pdf-protocols.js
- client/pages/sections/granted/summary-table.js
- client/pages/sections/protocols/animals.js
- client/pages/sections/protocols/protocol-sections.js
* dont include deprecated values in species selector categories
* add any deprecated species to the other category
* protocols now look up by value or name
> Bugfix - allow deprecated species

- client/constants/conditions.js
The field name in the condition was incorrect.
> Fix condition for purpose bred animals

- client/components/field.js
- client/components/repeater.js
previously we were swallowing errors in fields in a promise chain - inform users of these errors
> Bugfix - inform users of errors

- client/components/diff-window.js
- client/components/download-link/renderers/docx-renderer.js
- client/components/review-field.js
- client/helpers/index.js
* Abstracted species selector rendering logic
* Updated diff component to handle species
* Updated to handle permissible purposes
* Handle simple lists
> Bugfix - diff component for not-rte

- client/components/diff-window.js
If a field had options, try and lookup the label from options to show in diff
> Bugfix - lookup labels in diff

- client/actions/projects.js
- client/helpers/index.js
- client/pages/section.js
- client/pages/sections/protocols/protocols.js
moved logic to debounced sync to prevent evaluating conditions on every keystroke
> Move conditions eval logic

- client/components/conditions/conditions.js
To make it easier for automated tests to interact with particular conditions.
> Add class name to conditions

- client/components/static-section.js
* If a step is conditional, all fields in the step should be omitted if the condition is fasly
> Bugfix - hide conditional steps

- client/constants/conditions.js
* Added 'protocol' to continued use condition
> Tweak - amdend wording

- client/constants/conditions.js
* Added new line before `ol` to enforce list rendering
> Bugfix - transfer auth formatting

- assets/scss/projects.scss
- client/components/review-field.js
- client/helpers/index.js
- client/schema/v1/index.js
* added preserveHeirarchy option to reveal fields - this prevents children being flattened
* render children in scope
> Bugfix - fate of animals hierarchy

- client/actions/messaging.js
- client/components/error-boundary.js
* Added postError action
* Call with error details in ErrorBoundary
needs https://github.com/UKHomeOffice/asl-service/pull/170 to be bumped at same time
> Post errors

- client/actions/projects.js
- client/pages/index.js
- package-lock.json
- package.json
- views/components/phase-banner.jsx
Remove ability to create new projects and update shutdown date.
> Deprecate drafting tool

- client/components/editor/image/index.js
> Restrict image embeds to PNG and JPG files

- assets/scss/projects.scss
- client/components/application-summary.js
- client/components/changed-badge.js
- client/components/sections-link.js
- client/components/side-nav.js
- client/helpers/index.js
* Added noLabel option to changed component
* Abstacted getFields logic to get all nested fields for section
* added styling to changed component to appear as a dot
> Feature - added changed dots to side nav

- client/components/download-link/renderers/docx-renderer.js
* Added applicant name, establishment name and other establishments to front page of word export
* Needs corresponding change in asl-pages providing establishmentt
> Feature - add establishment info to word

- client/components/review.js
- client/constants/legal.js
- client/pages/sections/granted/project-summary.js
- client/schema/v1/index.js
- views/pdf/v0/index.jsx
* updated text, added alt label for reviewing duration - not a question.
* If review property on field, render this rather than the label
> Update to legal text

- client/schema/v1/index.js
* Removed hint text for reduction-estimation question
* Updated hint text for reduction-steps question
> Updated NTS hint text

- client/components/side-nav.js
* If a section repeats then add the name of the repeater to the list of fields
> Bugfix - changed indicators for repeating sections

- assets/scss/projects.scss
- client/components/details.js
- client/pages/sections/protocols/protocol-conditions.js
* Added react details component which adds handler for use in edge. Implemented for protocol general conditions
> Added Details component

- client/pages/sections/granted/protocol-objectives.js
- client/schema/v1/index.js
* Added objectives section for granted/pdf protocols
> Feature - objective protocols pdf

- client/components/changed-badge.js
- client/components/review-fields.js
- client/components/review.js
- client/pages/sections/protocols/steps.js
* Updated review component to use changed badge component rather than rando implementation
> Changed indicators on new protocol steps

- client/components/changed-badge.js
- client/components/diff-window.js
- client/components/review.js
* ChangedBadge assumes the redux store has been initialised, it does not when transferring a PPL.
* Check there are changes before trying to render
> Bugfix - dont try and render changed badge if no changes

- client/components/review-field.js
- client/helpers/index.js
- client/pages/sections/granted/project-summary.js
- client/schema/v0/index.js
- client/schema/v1/index.js
- views/pdf/v1/index.jsx
* Added permissible purposes to PDF and granted view for new PPLs
* Updated legacy to use permissible purposes field type to show answers in context
> Bugfix - permissible purposes

- client/components/diff-window.js
- client/components/review.js
* These values are false on render as they aren't calculated until later
> Bugfix - diff window

- assets/scss/projects.scss
This gives more space for the content
> Reduce margins on diff window modal

- .npmignore
- client/components/conditions/index.js
- client/components/retrospective-assessment.js
- client/helpers/retrospective-assessment.js
- package-lock.json
- package.json
- test/.eslintrc
- test/specs/helpers/retrospective-assessment.js
ASRU should be able to add an RA condition if one does not apply, and should see if one has been automatically applied, but it should not appear under the conditions section when viewing the granted licence because RA is already exposed in the "Project summary" section.
> Add ability to edit retrospective assessment condition

- assets/scss/projects.scss
- client/project-router.js
- package-lock.json
- package.json
Waiting for https://github.com/UKHomeOffice/asl-components/pull/106
> Improved licence / download header

- client/constants/conditions.js
* Include if project.transfer is true
> Feature - added transfer authoristion

- client/components/comments/comment.js
- client/components/conditions/condition.js
- client/components/conditions/conditions.js
- client/components/conditions/index.js
- client/pages/sections/granted/authorisations.js
- client/pages/sections/granted/conditions.js
- client/pages/sections/granted/project-summary.js
- client/pages/sections/legacy-conditions.js
- client/pages/sections/protocols/protocol-conditions.js
- package-lock.json
- package.json
- views/pdf/components/standard-conditions.js
- views/pdf/v0/index.jsx
- views/pdf/v1/index.jsx
* Added custom renderer for links user authored content
* Replaced ReactMarkdown with LinklessMarkdown
> Disallow links in comments

- client/schema/v1/index.js
It's a question so should have a question mark.
> Fix field label

- client/schema/shared/index.js
- client/schema/v0/index.js
- client/schema/v1/index.js
* Updated transfer section fields and nesting
* Add transfer to legacy - always showing
> Feature - transfer section updates

- client/components/establishment-selector.js
- client/schema/shared/index.js
* show transfer section if transferToEstablishment is set
* updated logic in component to not sync on page load - await changes
> Bugfix - add transfer of animals section if transfer

- client/schema/v1/index.js
* Removed fate-nts question, bring fate checkbox group to top level
> Bugfix - denest fate

- client/schema/v1/index.js
* Replaced killing method checkbox group with yes no radio
> Bugfix - update protocol fate killing method

- client/components/establishment-selector.js
* Updated to use establishmentName if not defined, fallback to another est
> Bugfix - display transfer proj name if user can see it

- assets/scss/projects.scss
- client/components/application-summary.js
* Added top margin to table cells
* Reduced section heading margin bottom
> Improve styling of application summary

- client/components/download-link/renderers/docx-renderer.js
* Render section label if present in protocol sections
> Bugfix - missing jusitifcation question intro

- client/components/download-link/renderers/docx-renderer.js
When rendering an image inside another node the renderer failed because `renderNode` pretends it has the document as the parent node. Except `addImage` doesn't exist on the parent node when it's _not_ the document, so the renderer throws with an error.
Add the document as a `const` in the top level scope rather than passing "probably the document" around as an argument so that it can be reliably referenced.
> Fix image rendering when nested inside other nodes

- client/components/field.js
- client/components/review-field.js
- client/pages/sections/repeater/review.js
* Use the existing repeater review to correctly set the prefix and render comments
> Bugfix - show comments in repeater

- assets/scss/projects.scss
- client/pages/sections/granted/pdf-protocols.js
- client/pages/sections/granted/summary-table.js
- client/pages/sections/protocols/index.js
- client/pages/sections/protocols/review.js
- client/pages/sections/protocols/summary-table.js
- client/project-router.js
* added summary table page
* added link to protocol views
* Updated existing protocol summary to include expandable row
> Feature - protocol summary table

- client/pages/sections/granted/pdf-protocols.js
* updated granted summary table column headings
* added optional className
* render children if provided
* only render sections if provided
> Feature - PDF protocols

- client/components/download-link/renderers/docx-renderer.js
Img width and height were lost in a previous change. Restore
> Bugfix - image dimensions

- client/components/diff-window.js
- client/components/review-field.js
- client/components/review-fields.js
- client/components/review.js
- client/pages/sections/repeater/review.js
* Updated continuation component to only show diff for parent element
* Removed comments/labels from children
* Fixed edit links for repeaters
> Bugfix - continuation fixes

- assets/scss/projects.scss
- client/components/other-species-selector.js
* Updated remove buttons on species selector to show links
* Updated styling to center vertically
* Only show remove links if items > 1
> Bugfix - replace remove buttons with links

- client/components/new-protocol-badge.js
- client/components/nts.js
- client/components/reordered-badge.js
- client/components/review-fields.js
- client/components/static-section.js
- client/pages/sections/establishments.js
- client/pages/sections/granted/pdf-protocols.js
- client/pages/sections/granted/protocol-objectives.js
- client/pages/sections/granted/protocol-steps.js
- client/pages/sections/granted/summary-table.js
- client/pages/sections/objectives/review.js
- client/pages/sections/protocols/sections.js
- client/reducers/application.js
- client/schema/v1/index.js
- views/pdf/v1/index.jsx
* Added fullApplication option when downloading a pdf
* Updated protocols to include repeating continued header
* added hacky white box to cover the protocol continued header on first page
* only sort protocol sections if granted
> Feature - Full application PDF

- client/components/retrospective-assessment.js
- client/helpers/retrospective-assessment.js
* Use raCompulsory property from init settings to determine if ra can be toggled
> Feature - RA as data

- client/pages/sections/protocols/legacy-animals.js
* Added type prop to repeater so prefix is correct
> Bugfix - legacy species changed labels

- client/components/playback.js
- client/helpers/index.js
- client/pages/sections/granted/project-summary.js
- client/pages/sections/objectives/index.js
- client/pages/sections/protocols/section.js
- client/schema/v1/experience.js
- client/schema/v1/index.js
- client/schema/v1/permissible-purpose.js
* Rebases #555 to remove the standalone changes, and preserve only the schema modifications
* Add permissible purpose section to granted PPL outputs
> Training PPLs

- client/components/side-nav.js
- client/pages/readonly.js
If a subsection is the active section then open that section of the left hand navigation by default
> Open active section in PPL side navigation

- client/pages/sections/training.js
- client/schema/v1/index.js
* This prevents the sync on new projects when saying training needs to be updated
> Bugfix - only update training complete if true

- client/components/download-link/renderers/docx-renderer.js
values is set the repeater item in repeaters, show conditionals require the whole project
> Bugfix - conditional reveals in repeaters

- assets/scss/projects.scss
- client/components/comments/comment.js
- client/components/comments/index.js
* Removed comment icon
* Removed heading border
* left align date
* Add comments count
> Feature - update comments styling

- client/components/nts.js
- client/pages/sections/nts.js
- client/schema/v1/index.js
Also:
* give the NTS page a H1
* rename the link from the section list
* hide the "continue" button in the NTS banner once accepted
> use different content at the top of the NTS edit page

- client/constants/protocol-conditions.js
- client/pages/sections/protocols/editable-protocols.js
- client/pages/sections/protocols/protocol-conditions.js
... and remove redundant asterisks.
> Add general constraints to protocol edit view

- assets/scss/_editor.scss
- client/components/editor/format-toolbar.js
Added labels to each button, hidden with css
> Accessibility fix - editor controls

- assets/scss/_editor.scss
- client/components/editor/blocks/render-block.js
* Added button on image hover to delete image
> Feature - delete image button

- assets/scss/projects.scss
- client/components/additional-availability.js
- client/components/establishment-selector.js
- client/components/field.js
- client/components/review-field.js
- client/helpers/get-locations.js
- client/pages/sections/granted/project-summary.js
- client/schema/v1/index.js
* Added additional availability field type
* Updated protocols est selector to look for linked est
> Feature - additional availability

- assets/scss/projects.scss
- client/components/additional-availability.js
- client/schema/v0/index.js
- client/schema/v1/index.js
* Use checkbox if one answer
* Add clear link to radios
* Remove hint text
* Move details summary beneath label
> AA interface changes

- client/actions/projects.js
- client/components/location-selector.js
- client/helpers/clean-protocols.js
- client/helpers/get-locations.js
* If transfer, use transfer to est for est selector
* Try to lookup est name from assoc ests
* uniq est names in protocol est
> Bugfix - transfer AA est

- client/components/establishment-selector.js
* We now store transferToEstName in data, use if present
> Bugfix - use est name from data

- client/constants/conditions.js
* Added new content for future conditions: reuse, marmosets, continued use and commercial slaughter
> Content - conditions

- client/components/changed-badge.js
- client/components/diff-window.js
- client/components/review.js
Add a comparison with the first submission made, so that changes in response to the initial review are still marked in later iterations.
> Add extra layer of comparison for PPL applications

- assets/scss/projects.scss
- package-lock.json
- package.json
~Waiting on https://github.com/UKHomeOffice/asl-components/pull/177 bump~
> Sticky headers

- client/components/playback.js
- client/pages/sections/objectives/review.js
* Playback project aim when looking at action plan in readonly
* Provide link back to the relevant section
> Fearture - playback aim

- assets/scss/projects.scss
- package-lock.json
- package.json
~waiting on https://github.com/UKHomeOffice/asl-components/pull/183~
> Give the modal a z-index boost to bring it higher than the header

- client/actions/projects.js
- client/components/diff-window.js
- client/reducers/question-versions.js
This should now load the diff data from the server response instead of comparing locally.
> Refactor diff window component

- client/components/diff-window.js
This needed the complete project data to get the value, but that wasn't being loaded from state.
> Fix animal quantities comparison

- assets/scss/projects.scss
- client/actions/projects.js
- client/components/application-summary.js
- client/components/diff-window.js
- client/components/editor/index.js
- client/components/field.js
- client/components/nts-writing-tips.js
- client/components/ra-hint.js
- client/components/ra-playback-hint.js
- client/components/ra-side-panel.js
- client/components/ra-summary.js
- client/components/review.js
- client/pages/project.js
- client/pages/section.js
- client/project-router.js
- client/schema/index.js
- client/schema/ra/index.js
* Added schema for RA schemaVersion
* Added ra playback component for playing back questions for relevant project type
* Updated diff window to allow ra type versions* added nts writing tips
> Feature - RA

- client/components/nts-writing-tips.js
- client/components/ra-declaration.js
- client/components/ra-hint.js
- client/components/ra-side-panel.js
- client/pages/project.js
- client/project-router.js
- client/schema/ra/index.js
* Show RA declaration if no answers completed
* Updated wording
> Feature - RA Declaration

- client/schema/v1/index.js
> Change the CTA for transfer of animals

- client/components/static-section.js
- client/pages/sections/protocols/sections.js
- client/pages/sections/protocols/steps.js
- views/pdf/v1/index.jsx
and show the missing questions in protocol steps.
> Add missing hint text to application pdf

- client/components/playback.js
- client/components/review-field.js
- client/pages/sections/objectives/review.js
> Remove generated hint text with link from application PDF

- client/components/download-link/renderers/docx-renderer.js
* est name was being split as it is not an array
> Bugfix - docx protocol est

- client/pages/sections/protocols/legacy-animals.js
* Species details cannot be removed from legacy protocols
> Bugfix - remove species

- client/pages/sections/granted/project-summary.js
- client/project-router.js
- views/pdf/v0/index.jsx
Needs https://github.com/UKHomeOffice/asl-public-api/pull/312
> Add version holder to props

- .eslintrc
- client/constants/conditions.js
- client/pages/sections/objectives/index.js
- client/pages/sections/objectives/review.js
- client/schema/shared/index.js
- client/schema/v1/index.js
This is mostly `\u200B` zero-width spaces that make doing text-based selenium selectors fail in unexpected ways.
Add an eslint rule to not allow non-standard whitespace characters.
> Remove hidden whitespace

- assets/scss/projects.scss
- client/components/application-summary.js
- client/components/next-steps.js
- client/components/section-nav.js
- client/components/static-section.js
* Added section nav component for next/previous sections
* Added next steps component to application summary
> Feature - section nav

- client/components/review.js
- client/pages/sections/training.js
Marks the question about training being complete as a `comments-only` which means that it does not create any output _except_ comments.
> Allow commenting on training section

- client/components/download-link/renderers/docx-renderer.js
Custom styles dont have any hierachy and aren't added to navigation in word. Adjusted to use h1 h2 and h3
> Bugfix - heading hierachy

- assets/scss/projects.scss
- client/components/other-species-selector.js
- client/components/species-selector.js
* updated labels for other species
* set max width to 200px for other species
> Species selector labels

- client/components/application-summary.js
- client/components/submit.js
- client/pages/sections/training.js
* Abstracted submit component
* Show cannot submit text if cannot submit
> Feature - collab perms

- client/components/submit.js
Dont show amendment/application text for ra
> Bugfix - ra submit text

- client/components/editor/index.js
- client/components/field.js
- client/components/ra-playback-hint.js
- client/components/review-field.js
* React markdown now uses children rather than source
* Updated all occurances of source
> bugfix - RTE hints

- client/components/editor/blocks/render-block.js
* images are blocks, they do not have text, we still want to render them
> Bugfix - restore images

- client/pages/sections/protocols/sections.js
* Added protocol number to beginning of protocol section headers, digital edit and read
> Feature - added protocol number

- client/components/download-link/renderers/docx-renderer.js
* Updated header sizes to enforce hierachy
* Added new header level
> Tweak - word header sizes

- assets/scss/projects.scss
> Prevent field width shrinking when add another clicked

- assets/scss/projects.scss
Needs https://github.com/UKHomeOffice/asl-components/pull/234
> remove accordion toggle styling and inherit from component

- assets/scss/projects.scss
- client/components/application-summary.js
- client/components/conditions/conditions.js
- client/components/conditions/index.js
- client/components/next-steps.js
- client/components/preview-licence.js
- client/components/section-nav.js
- client/components/side-nav.js
- client/pages/sections/granted/authorisations.js
- client/pages/sections/granted/project-summary.js
- client/project-router.js
- client/schema/v1/index.js
* Added preview component
* updated components to not be editable if in preview mode
* Added no conditions label
> Feature - preview

- client/constants/conditions.js
Include a filter for the specific species that are relevant to this condition.
> Refine trigger for non-purpose-bred schedule 2 species

- client/constants/conditions.js
The question that triggers this condition is dependent on _either_ additional establishments or a transfer taking place, so need to incllude that in the condition trigger.
> Include transfers in trigger for transfer of animals condition

- client/components/application-summary.js
This looked like it wasn't used, but the entire component props are passed to the `show` function, and that is expected to include `showConditions`.
> Restore `showConditions` prop to application summary

- client/components/application-summary.js
- client/components/submit.js
- client/schema/v1/index.js
* Remove content about submitting application to Home Office
* Add a hyphen to `Non-technical summary`
* `Back to...` => `Go to...`
> Content changes to PPL/RA application

- client/components/establishment-selector.js
- client/pages/sections/establishments/establishments.js
- client/pages/sections/establishments/index.js
- package-lock.json
- Added new text and warning field to match design
- Used establishment selector component with minor changes in order to make the text bigger to better match the design
See design and result attached.
> Edit establishments page to add more info when adding additional establishments

- client/components/establishment-selector.js
- client/pages/sections/establishments/establishments.js
- client/pages/sections/establishments/index.js
- package-lock.json
Reverts UKHomeOffice/asl-projects#799
> Revert "Edit establishments page to add more info when adding additional establishments"

- client/components/editor/blocks/render-block.js
I was confusing the arguments of `useSelector` and `useEffect`. The empty array as a second argument here is incorrect.
> Fix erroneous use of `useSelector`

- client/components/conditions/add-conditions.js
Previously it was passing a string back to the setEdited
> Bugfix: Condition component now passes an object onUpdate

- client/schema/v1/index.js
ASL-4067 - add extra hint text to make the GA questions clearer.
> Add hint text for GA questions

- client/components/editable.js
Fix for [ASL-4076](https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4076)
Changed the old class component into a function component
Fixed issue where existing reminders would only be added to the state after a change
> Refactor editable component to make it a function component

- client/components/modal.js
This captures the tab & shift+tab to check if the activeElement is the last and tab forward it will reset focus to the first focusable element, otherwise if it is the first element and tab back it will reset focus to the focusable lastElement.
Also converted to a functional component
> ASL-1673/ASL-1672 - Escape to close Modal and tabs stay within Modal

- assets/scss/projects.scss
- client/components/sync-handler.js
- client/project-router.js
- package-lock.json
- package.json
When editing a PPL, add a component to the document header to show `Saving...`/`Saved` when changes are being written to the server.
> Add sync status to PPL application document header

- client/project-router.js
- package-lock.json
- package.json
* Close the banner by default on page load in the client.
* Allow clicking the whole banner header to toggle the visibility as per the banners on other pages
> Fix toggle state of PPL status banners

- client/components/conditions/add-conditions.js
- client/components/conditions/condition.js
- client/components/conditions/conditions.js
Allows users to add reminders to conditions as the condition is being created
> Add reminders with conditions 

- client/components/next-steps.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4028
> Fix PPL next steps

- client/constants/conditions.js
This should have been changed before, but only the protocol level condition was changed.
> Fix content for project level POLE condition

- client/actions/projects.js
The version data is extended on the client with the id, which means it will always differ from the server value, which does not have an id value.
This prevents an error being thrown in RAs where no omissions are defined on the server side because an RA does not include any server computed properties.
Also improve error handling so that any client side errors in the sync pipeline are correctly logged. Currently if there is an error thrown during the sync pipeline (such as the above) it is not reported.
> Default checksum omission to `id`

- client/components/submit.js
Edit submit component to change 'Return to project overview' link placement
Add instances in order to style differently based on conditionals
Before
After
> Fix back to project link styling

- client/components/ra-playback-hint.js
- client/schema/ra/index.js
Update text as per ticket and document attached to [ASSB-1240](https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1240):
> ASL-4194 - Retrospective assessment guidance text

- client/project-router.js
- package-lock.json
- package.json
WIP until https://github.com/UKHomeOffice/asl-components/pull/280 has been merged
> ASL-4186 - Add guidance text and link to project header when editing

- client/helpers/index.js
- client/helpers/steps.js
- client/pages/sections/protocols/protocols.js
- client/pages/sections/protocols/steps.js
Reverts old way of fixing the comment issue as this broke the change badges
New way of fixing it (bit of a hacky way but works)
> ASSB-1285: Revert old fix and do it a different way

- client/pages/sections/protocols/protocols.js
The previous way caused an error when editing protocols
> Change way comments are flagged to fix error

- client/schema/v1/index.js
* Does not add any additional validation
* Just hint that we expect numbers, but the form still accepts text
> Add additional hint text for max animals

- client/components/review.js
- client/pages/sections/protocols/steps.js
- package-lock.json
- package.json
Reverts UKHomeOffice/asl-projects#893
> Revert "Bugfix/assb 1345 without diff window regression"

- assets/scss/projects.scss
- client/components/conditions/condition.js
- client/components/editable.js
- client/constants/conditions.js
- package-lock.json
- package.json
- Use version of components with markdown fixes
- Add hint about using markdown
- Fix styling issues
> [ASL4380] Expand standard antibody condition

- package-lock.json
- package.json
Update dependency asl-components from 13.0.0 to 13.2.1; Update asl-projects version from 15.0.2 to 15.0.3
> Update dependency asl-components from 13.0.0 to 13.2.1

- client/components/application-summary.js
- client/components/comments/index.js
- client/components/review-fields.js
- client/components/review.js
- client/helpers/index.js
- client/pages/sections/protocols/protocol-sections.js
- client/pages/sections/protocols/protocols.js
- client/pages/sections/protocols/steps.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4457
> [ASL-4457] Reusable steps comment fixes

- package-lock.json
- package.json
Bump asl-projects from 15.2.1 to 15.3.0; Bump dependency asl-components from 13.4.1 to 13.5.0
> Bump asl-projects from 15.2.1 to 15.3.0

- client/components/diff-window.js
- client/helpers/array-diff.js
- package-lock.json
- package.json
- test/specs/helpers/array-diff.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4532
> [ASL-4532] bug: Aim Keywords highlighting issue

- client/components/diff-window.js
- client/helpers/array-diff.js
- package-lock.json
- package.json
- test/specs/helpers/array-diff.js
bug: Aim Keywords highlighting issue
> [ASL-4532] bug: Aim Keywords highlighting issue (#915)

- assets/scss/projects.scss
- package-lock.json
- package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4554
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1401
> [ASL-4554] Set background for `code` to transparent in protocol step headers

- client/components/diff-window.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4533
> Adding code to highlight changes done for radio selection.

- client/components/checkbox.js
- package-lock.json
- package.json
quote mark added as UCD design.
> quote added to the checkbox values in nts -modal.

- client/pages/sections/protocols/steps.js
- package-lock.json
- package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1397
> [ASSB-1397] Remove edit just this step link

- client/components/checkbox.js
- package-lock.json
- package.json
fixed static wording transforming checkbox values eliminating '-' between words and also applied conditions on the kept alive option.
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1414
> typo on kept-alive option

- client/schema/index.js
- package-lock.json
- package.json
- views/pdf/v1/index.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4590
> [ASL-4590] Limit injecting licence holder field to PDF

- client/helpers/render-fields-in-protocol.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1425
> [ASSB-1425] Kept alive should only show in protocols when kept alive is ticked in NTS

- client/components/checkbox.js
- client/helpers/has-existing-data-for-checkbox.js
- package-lock.json
- package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1441
> [ASSB-1441] Show modal if deselected fate is ticked in any protocol

- client/components/download-link/renderers/docx-renderer.js
- client/helpers/index.js
- package-lock.json
- package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4592
Catch errors when rendering a value as a date
> [ASL-4592] Previous project expiry allows invalid date

- client/components/editable.js
- client/components/reminders.js
- client/constants/conditions.js
- package-lock.json
- package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASSB-1444
> [ASSB-1444] Update copy to match asl-components changes

- client/helpers/field-change-detection.js
Fix undefined error in `hasDatabaseChange` function
> Fix undefined error in hasDatabaseChange function

- package-lock.json
- package.json
Bump version to 15.8.3 for correct tagging
> Bump version to 15.8.3 for correct tagging

- package-lock.json
- package.json
change hightlight code commented.
> reverted changes for change-hightlight

- .drone-1.0.yml
- package-lock.json
- package.json
> node v22.14.0
